### ISSUE TITLE
Mandrill Email Open Click Bounce activities not arriving

### ISSUE THREAD

**Issue by mcollopy** [JMAConsulting/biz.jmaconsulting.mte#103]
Haven't received any Mandrill Email Open, Click or Bounce activities since Nov 5th lat year.
Only Sent is appearing since then.
Updated to Civi version 4.6.14 and MAndrill Extension 2.0 today with no luck.
Also getting some Mandrill Webhook errors 'Error: POST to /civicrm/ajax/mte/callback?mandrillSecret=xxxxx  failed with 500:'
Please advise what I can do to troubleshoot/fix.
Thanks

**Comment by Edzelopez** [comment]
Hi @mcollopy, 

Could you please paste the entire webhook URL here (excluding the mandrillSecret key of course) so I can have a look?

**Comment by mcollopy** [comment]
Here you go http://www.audienceware.co.uk/civicrm/ajax/mte/callback?mandrillSecret=

Thanks Edsel

On 22/03/2016, at 12:31 AM, Edsel Roque Lopez wrote:

> Hi @mcollopy,
> 
> Could you please paste the entire webhook URL here (excluding the mandrillSecret key of course) so I can have a look?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

Mick Collopy
Audienceware Pty Ltd
e. mick@audienceware.com
w. www.audienceware.com.au
m. +61(0)420476206

**Comment by mcollopy** [comment]
Furthermore I'm using a single Mandrill account for multiple sites, and all sites activities are coming in on the webhooks.  How do I filter by API key or sub-account?

**Comment by pradpnayak** [comment]
Hi Mick,

Could you please try the new beta version. There were few issues for 2.0 version which were fixed in 2.1.beta. 
Try Updating the extension from 2.0 to 2.1.beta

You can download it from https://civicrm.org/extensions/mandrill-email

I believe since the latest version is a beta version it doesn't show up as automatic download on civicrm extension page. So you will need to manually download and update the extension.

The extension is not handled as per sub account or api key for recording any events from Mandrill in case of multiple site using same account. Th extension will create mandrill event activity if the site gets call backs from mandrill.

HTH
Pradeep

**Comment by mcollopy** [comment]
Hi Pradeep - I am actually using 2.1, still not receiving opens and clicks.
I installed it on another site and it is working however.
How can I troubleshoot this?

Also, RE filtering by Key MAndrill Support provided a solution which works - using Rules as follows:

> Currently, there isn't a pre-defined method for routing webhook data based on subaccount or API key data. However, you can set this up by using our Rules engine, though the set up process will be slightly more involved as you'll need to set a different rule for each trigger you'd like to use. So, for example, if you'd like to receive webhook data for all messages sent using the API key awuk, you'll follow these steps.
> 
> First, set a webhook URL without any trigger and have the webhook URL verified.
> 
> Next, you'll set a rule that looks like this:
> 
> if a message is sent and all of the following conditions are met:
> 
> api key is awuk
> 
> then do this:
> send event to webhook http://awukwebhookurl
> 
> Of course, you'll need to set a different rule for each trigger you'd like to use though this does give a bit more control over where the webhook event is sent and how it is routed.
> 
> Please let me know if you have any other questions and we're glad to help.
